# Generated by Django 3.1.6 on 2021-03-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trapezna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='building',
            field=models.CharField(choices=[('Kozelnytska 2A', 'BFS'), ('Sventsitskoho', 'Sventsa'), ('FBF', 'FBF')], default=('Kozelnytska 2A', 'BFS'), max_length=255),
        ),
    ]
