# Generated by Django 3.1.6 on 2021-04-21 21:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('picture', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_by', models.CharField(max_length=200)),
                ('lecturer', models.CharField(max_length=200)),
                ('category', models.IntegerField(choices=[(1, 'Sociology'), (2, 'Programming'), (3, 'Lifeworks')])),
                ('location', models.CharField(choices=[(1, 'Sheptytsky Center'), (2, 'Kozelnytska 2a'), (3, 'Sventsitskoho 17'), (4, 'Khutorivka')], max_length=300)),
                ('event_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_online', models.BooleanField(default=False)),
                ('event_online_meeting_link', models.CharField(default=None, max_length=600)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=200)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event id')),
            ],
            options={
                'db_table': 'event_favorites',
            },
        ),
    ]
