# Generated by Django 3.1.6 on 2021-05-21 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('r', 'To be reviewd'), ('p', 'Published'), ('w', 'Withdrawn')], default='d', max_length=1)),
                ('picture_url', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_by', models.CharField(max_length=200)),
                ('lecturer', models.CharField(max_length=200)),
                ('category', models.IntegerField(choices=[(1, 'Sociology'), (2, 'Programming'), (3, 'Lifeworks')])),
                ('location', models.CharField(choices=[('c', 'Sheptytsky Center'), ('k', 'Kozelnytska 2a'), ('s', 'Sventsitskoho 17'), ('h', 'Khutorivka')], max_length=300)),
                ('event_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_online', models.BooleanField(default=False)),
                ('event_online_meeting_link', models.CharField(blank=True, max_length=600)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=200)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event id')),
            ],
            options={
                'db_table': 'event_favorites',
            },
        ),
    ]
