# Generated by Django 3.1.6 on 2021-05-24 17:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[(1, 'Sociology'), (2, 'Programming'), (3, 'Lifeworks')], max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('r', 'To be reviewd'), ('p', 'Published'), ('w', 'Withdrawn')], default='d', max_length=1)),
                ('picture', models.ImageField(blank=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_by', models.CharField(max_length=200)),
                ('lecturer', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='1', max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('location', models.CharField(blank=True, max_length=3000)),
                ('event_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_online', models.BooleanField(default=False)),
                ('event_online_meeting_link', models.CharField(blank=True, max_length=600)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=200)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event id')),
            ],
            options={
                'db_table': 'event_favorites',
            },
        ),
    ]
