# Generated by Django 3.1.6 on 2021-04-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='picture',
            new_name='picture_url',
        ),
    ]
