# Generated by Django 3.1.6 on 2021-05-21 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True),
        ),
    ]
