# Generated by Django 3.1.6 on 2021-05-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('c', 'Sheptytsky Center'), ('k', 'Kozelnytska 2a'), ('s', 'Sventsitskoho 17'), ('h', 'Khutorivka')], max_length=300),
        ),
    ]
