# Generated by Django 3.1.6 on 2021-05-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210521_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(default=1000, primary_key=True, serialize=False, unique=True),
        ),
    ]
