# Generated by Django 3.1.6 on 2021-05-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('organization_name', models.CharField(max_length=100)),
                ('head', models.CharField(max_length=1000)),
                ('secretary', models.CharField(max_length=1000)),
                ('financier', models.CharField(max_length=1000)),
                ('members', models.CharField(max_length=10000)),
                ('media', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
    ]
