# Generated by Django 3.1.6 on 2021-05-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='web_site',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
