# Generated by Django 3.1.6 on 2021-05-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20210516_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
