# Generated by Django 3.1.6 on 2021-05-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('emailucu', models.EmailField(max_length=254)),
                ('lastnameukr', models.CharField(max_length=1000)),
                ('firstnameukr', models.CharField(max_length=1000)),
                ('lastnameeng', models.CharField(max_length=1000)),
                ('firstnameeng', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('department', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
    ]
