# Generated by Django 3.1.6 on 2021-05-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20210517_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
