# Generated by Django 3.1.6 on 2021-05-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20210517_2027'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='phonenumber',
            table='phone_numbers',
        ),
    ]
