# Generated by Django 3.1.6 on 2021-05-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20210517_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='emailucu',
            field=models.CharField(max_length=1000),
        ),
    ]
