# Generated by Django 3.1.6 on 2021-05-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
